"""Changing id to str

Revision ID: 496af740e2e3
Revises: 262dbc2824d4
Create Date: 2025-06-14 19:20:20.765338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496af740e2e3'
down_revision = '262dbc2824d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
